// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyALBxIjYqbuwKKC0Vm5d9uFCZKOXigTeKY',
    appId: '1:235892732833:web:6320647af9e8237b1891e0',
    messagingSenderId: '235892732833',
    projectId: 'arkatrack',
    authDomain: 'arkatrack.firebaseapp.com',
    storageBucket: 'arkatrack.firebasestorage.app',
    measurementId: 'G-5K0V0X90CW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQiZUsNZAWd2YW-acJ96LkGYUVov5t4MA',
    appId: '1:235892732833:android:a49f22b4ea7b3ff31891e0',
    messagingSenderId: '235892732833',
    projectId: 'arkatrack',
    storageBucket: 'arkatrack.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMTUkspICujYxcv9FIGmwrihn-MiH0UvM',
    appId: '1:235892732833:ios:2b38c0230c19e5431891e0',
    messagingSenderId: '235892732833',
    projectId: 'arkatrack',
    storageBucket: 'arkatrack.firebasestorage.app',
    iosBundleId: 'com.example.arkatrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMTUkspICujYxcv9FIGmwrihn-MiH0UvM',
    appId: '1:235892732833:ios:2b38c0230c19e5431891e0',
    messagingSenderId: '235892732833',
    projectId: 'arkatrack',
    storageBucket: 'arkatrack.firebasestorage.app',
    iosBundleId: 'com.example.arkatrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyALBxIjYqbuwKKC0Vm5d9uFCZKOXigTeKY',
    appId: '1:235892732833:web:5cb81f19120edd191891e0',
    messagingSenderId: '235892732833',
    projectId: 'arkatrack',
    authDomain: 'arkatrack.firebaseapp.com',
    storageBucket: 'arkatrack.firebasestorage.app',
    measurementId: 'G-CLW2098V3H',
  );
}
